name: My First GitHub Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # using ubuntu as the base image

    strategy:
      matrix:
        python-version: [3.8, 3.9] # using 2 versions of python for better availability and to run on the base image 

    steps:
    - uses: actions/checkout@v3 # @v3 is just the version of the plugin 
    - name: Set up Python
      uses: actions/setup-python@v2 # @v2 is just the version of the plugin and the version of Python
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
